### ISSUE TITLE
Publish latest version with scala 2.11

### ISSUE THREAD

**Issue by allantl** [toolsplus/atlassian-connect-jwt-scala#23]
It seems that you forgot to publish the latest version to scala 2.11.

Can you help me to publish it?

Thanks

**Comment by tbinna** [comment]
Hi @allantl, I just published version 0.1.6 for Scala 2.11. Seems most of the past few version have not been published for Scala 2.11. I will make sure future releases include Scala 2.11 again. Sorry about that.

If I find some time I'll look into backing the release process into Travis. Should be quite easy.
